--DROP TABLE training_web_application.admins;
--DROP TABLE training_web_application.third_table;
--DROP TABLE training_web_application.users;
--DROP SCHEMA training_web_application RESTRICT;

CREATE SCHEMA training_web_application;

CREATE TABLE training_web_application.users (
id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
login VARCHAR(20) NOT NULL,
password VARCHAR(20) NOT NULL,
name VARCHAR(20) NOT NULL,
surname VARCHAR(20) NOT NULL,
email VARCHAR(33) NOT NULL,
access Boolean NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE training_web_application.admins (
id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
login VARCHAR(20) NOT NULL,
password VARCHAR(20) NOT NULL,
PRIMARY KEY (id)
);

/*
CREATE TABLE training_web_application.third_table (
id_student INT NOT NULL,
id_course INT NOT NULL,
grade CHAR(1) DEFAULT ''
);
*/

/*
CREATE INDEX key_id_student
ON project_web_application.third_table (id_student);
CREATE INDEX key_id_course
ON project_web_application.third_table (id_course);
*/

/*
ALTER TABLE project_web_application.third_table
ADD CONSTRAINT key_student
FOREIGN KEY (id_student)
REFERENCES project_web_application.students (id)
ON DELETE CASCADE;
ALTER TABLE project_web_application.third_table
ADD CONSTRAINT key_course
FOREIGN KEY (id_course)
REFERENCES project_web_application.courses (id)
  ON DELETE CASCADE;
*/

INSERT INTO training_web_application.admins (login, password) VALUES ('admin', 'admin');